# Uncomment the next line to define a global platform for your project
#platform :ios, '8.0'

target 'desafio-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for desafio-ios
  pod 'RxCocoa',    '~> 3.0.1'
  pod 'Haneke'
  pod 'Moya-ObjectMapper/RxSwift', :git => 'https://github.com/ivanbruel/Moya-ObjectMapper'
  
  target 'desafio-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'desafio-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
