# Uncomment the next line to define a global platform for your project
#platform :ios, '8.0'

target 'desafio-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Haneke'
  pod 'Action'
  pod 'WebLinking', :git => 'https://github.com/kylef/WebLinking.swift', :commit => 'fddbacc30deab8afe12ce1d3b78bd27c593a0c29'
  pod 'Moya-ObjectMapper/RxSwift', :git => 'https://github.com/klevison/Moya-ObjectMapper', :commit => '3110c3d90921bfc79df9a86a9fdb69b41d19b57a'
  pod 'Moya', :git => 'https://github.com/Moya/Moya'
  pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift'
  
  target 'desafio-iosTests' do
    inherit! :search_paths
    pod 'RxTest'
  end

  target 'desafio-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
